# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffd13abf089a042af9f916dd8fd19d10dca7e762d9f8374b60b61de4dd35d2ee964c14b2ebf7bc4a804be259b19a75c0a22d68105a364504c6fe40976455b0ac

test:
  secret_key_base: 11f27e3b208db08c8096d0d664e5dcae64a69940fd746f708ecbe3404ada4a5cfcabb57df22b80edde5f6e1329a3005efc60370e7452b5a4c5f041cecffef5d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
